# Generated by Django 5.1.2 on 2024-11-01 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DomTrenirovki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50, verbose_name='Упражнение')),
                ('quantity', models.CharField(max_length=50, verbose_name='Количество раз')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Тренировки дом',
                'verbose_name_plural': 'Тренировки дома',
            },
        ),
        migrations.CreateModel(
            name='Pitanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pit_card_name', models.CharField(max_length=100, verbose_name='Название вида питания')),
                ('image', models.ImageField(upload_to='images/')),
                ('kall_text', models.CharField(max_length=255, verbose_name='Подбирание питания по категории')),
                ('kall_description', models.TextField(verbose_name='Рекомендации по подбору питания')),
                ('kall_text_one', models.CharField(max_length=255, verbose_name='Составленик рациона')),
                ('kall_description_one', models.TextField(verbose_name='Схема рациона питания')),
                ('kall_text_two', models.CharField(max_length=255, verbose_name='Ежедневный рацион питания')),
                ('kall_description_two', models.TextField(verbose_name='Схема ежедневного рациона питания')),
            ],
            options={
                'verbose_name': 'Питание и диета',
                'verbose_name_plural': 'Питание и диеты',
            },
        ),
        migrations.CreateModel(
            name='SpecTren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exer', models.CharField(max_length=50, verbose_name='Упражнение')),
                ('exer_one', models.CharField(max_length=50, verbose_name='Упражнение1')),
            ],
            options={
                'verbose_name': 'Специальная тренировка',
                'verbose_name_plural': 'Специальные тренировки',
            },
        ),
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Название абонемента')),
                ('training', models.CharField(default='безлимит(месяц)', max_length=100, verbose_name='Количество тренеровок')),
                ('descriptions', models.CharField(max_length=100, verbose_name='Скидка')),
                ('times', models.CharField(max_length=45, verbose_name=' Сколько человек приобрело')),
                ('prices', models.CharField(max_length=80, verbose_name='Стоимость абонемента')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnes_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=255, verbose_name='ФИО тренера')),
                ('det_title', models.CharField(max_length=100, verbose_name='Опыт работы')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('describing_trener', models.CharField(default='Не указано', max_length=255, verbose_name='Награды')),
                ('lessons_tren', models.CharField(default='Не указано', max_length=255, verbose_name='Цена занятий')),
                ('contact', models.CharField(default='Не указано', max_length=30, verbose_name='Контакты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnes_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Zal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название зала')),
                ('detail_title', models.CharField(max_length=100, verbose_name='Оценка зала')),
                ('imo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(verbose_name='Описание зала')),
                ('adress', models.CharField(default='ул. Абиша Кекилбайулы, 38А/1, Алматы (этаж 1)', max_length=255, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=25, verbose_name='телефон')),
                ('time', models.CharField(default='06:00–23:00', max_length=25, verbose_name=' Рабочие часы')),
                ('price', models.CharField(max_length=80, verbose_name='Стоимость абонемента')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnes_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
