# Generated by Django 5.1.2 on 2024-11-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectren',
            name='exercise',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='spectren',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spectren',
            name='times',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='количество раз'),
        ),
    ]
